### ISSUE TITLE
Dashboard : toggle switch

### ISSUE THREAD

**Issue by lmorel3** [Unleash/unleash#1148]
Hello,

We don't really understand why you've removed the toggle switch used to enabled/disable features directly on the dashboard. It was really practical to have an overview of every statuses. :)

Before :
![image](https://user-images.githubusercontent.com/1393808/144209220-86b91c1f-cc63-43b7-bf8e-1443cc26ddd6.png)

After :
![image](https://user-images.githubusercontent.com/1393808/144209355-58275017-035c-4ced-b71f-d9116fd9862e.png)

Can you at least reimplement a read-only switch please (it might be configurable ?) ? I can open a PR if needed.

**Comment by ivarconr** [comment]
Hi @lmorel3, 

Thanks for your feedback!  I can understand that this feels a bit confusing. 

We are pushing towards the project oriented view (and the feature toggle list will server more as a search across all projects. Because each project can take a different list of environments it can be quite confusing to have the switches in a list of toggles that spans projects. 

from v4.3 the project view will contain the following view (also available in the Open-Source Edition):
![image](https://user-images.githubusercontent.com/158948/144260286-2acbefc7-95c5-47cb-82e6-9b2df4737599.png)

We believe this answers your immediate need to see the toggle enabled status per toggle. 

We might introduce more information in the feature toggles view later, but we will probably keep it as a read-only view, as a user will usually have different permissions per projects, and as mentioned, each project can be configured with a different set of environments.
