### ISSUE TITLE
Toggle Event log not showing in UI

### ISSUE THREAD

**Issue by funkswing** [Unleash/unleash#1299]
The feature flag event logs are not showing up in the UI.

Feature flag Event log
 - as an Admin, the page is stuck on "fetching.."
 - as an Editor, it says "You cannot perform this action"

No errors in the logs

Global Event log
 - works for Admin (as expected)

Unleash 4.4.4 (open-source)
Upgraded to v4 from v3 recently, had been using v3 for 4 four years prior.

**Comment by ivarconr** [comment]
Sounds like there could be a bug in the event log handling for that version. We did quite a lot of changes to the event log in v4.4. It could also be errors to the migration job converting from the old to the new format. 

1. Do you see any errors in the console.log in browser or in the serer logs?
2. Can you share json-blob of the log events not working? 
3. Does the Event API work for the toggle (https://hostname/api/admin/events/ToggleName) 
4. Does a new toggle get the correct event log?
 
(feel free to share privately with me on [slack](https://slack.unleash.run)

**Comment by ivarconr** [comment]
I have investigated a bit more and figured out whats happening. We changed the format, where the feature_name was added as a separate column to the "events" table, instead of just being part of the data payload. 

Unfortunate, but there is a missing migration for this, so old feature events is no longer returned when querying for feature toggle  specific events. This only affects the `feature-created` and `feature-updated` events. 

New events will have the feature_name set, but the old events does not. Luckily the data still exists, we just need to find a way to populate that column.

**Comment by ivarconr** [comment]
We will not be able to maintain diff for old events, as we have somewhat change the calculation a bit. Previously you had to compute it on the fly by comparing prev and current event (across different event types). While we now encode the current state and pre state in to the event itself. 

never the less, we should be able to find and show old events, as long as they have the "feature_name" populated. I have created a migration for this is #1300.
