### ISSUE TITLE
[Question]: Is it safe to delete the default environment?

### ISSUE THREAD

**Issue by Meemaw** [Unleash/unleash#1353]
Hey 👋 

As the title says, I would like to know if it's safe to delete the default environment. As I understand it is there for backwards compatibility, and as such should not be relevant for new projects.

**Comment by thomasheartman** [comment]
Hi! 👋🏼 

Good question! And yes, it _is_ there for backwards compatibility. However, we need to make absolutely sure that removing it doesn't break anything before we allow users to delete it. It's safe in theory, but because we haven't tested thoroughly, we can't recommend that you do it. Both the UI and the API has guards in place to prevent you from deleting it, and while you _could_ (as in: it's possible) delete it from the database directly, we really recommend that you don't.

That said, you can of course _disable_ the environment; that's perfectly safe! Do you have a use case where that is not sufficient? Is there any reason you'd want to delete it entirely?

**Comment by Meemaw** [comment]
Oh, actually disabling it works fine. Just wanted to get rid of it in the UI, so it doesn't confuse people. Thanks for the response!
