### ISSUE TITLE
how to enable feature toggle only for specific environment

### ISSUE THREAD

**Issue by viramjain1999** [Unleash/unleash#1367]
I have three different env's I want to toggle a flag for specific env how can I do through api ?
is there is any way to pass the environment name
here is my code 

function offFeatureFlag(){
  axios({url:"https://unleash.hostname/api/admin/features/toggleName/toggle/off",
method: "post",
    
  headers: {
    Authorization: `${"my token"}`,
  
  },

})
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });
}

**Comment by ivarconr** [comment]
Hi, that is the legacy api, pre environments. 

See: https://docs.getunleash.io/api/admin/feature-toggles-v2#enable-env

**Comment by viramjain1999** [comment]
I am trying to turn off feature flag through legacy api but I am getting error
here is my code 
function offFeatureFlag(){
  axios({url:"https://host.name/api/admin/projects/default/features/feature-name/environments/development/toggle/off",
    
  headers: {
    Authorization: `${"my token"}`,
  
  },

method: "post",


})
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });
}
when I execute above function I am getting this error

 **Request failed with status code 404**
> Hi, that is the legacy api, pre environments.
> 
> See: https://docs.getunleash.io/api/admin/feature-toggles-v2#enable-env

**Comment by viramjain1999** [comment]
can anyone help how can I toggle feature flag only for a specific environments do we have an api to do that ? I tried above two ways but it is not working for me

**Comment by viramjain13** [comment]
Here is my StackOverflow post link [https://stackoverflow.com/questions/71210640/how-to-toggle-unleash-feature-flag-through-api-for-a-specific-environments](url)

**Comment by thomasheartman** [comment]
@viramjain13 and @viramjain1999 (are you the same person?): what version of Unleash are you using? And can you show me what value Axios provides for the `content-type` header? Judging by the error message, it seems that Unleash isn't getting the `content-type` it expects.

We've had some issues previously where libraries have sent `application/json;charset=utf8` instead of just `application/json`, which Unleash had trouble parsing up until recently. Could you try explicitly setting the `content-type` header to `application/json`?

**Comment by viramjain1999** [comment]
thanks @thomasheartman I changed the content-type to application/json and it works for me
