### ISSUE TITLE
What value would return if unleash server is down

### ISSUE THREAD

**Issue by ljcljc** [Unleash/unleash#1371]
I want to know if unleash server is down. Would the sdk return error, or just return False.

e.g.
if (unleash.isEnabled('proxy.demo')) {
    // do something
  }

Should I catch exception in my code specifically for this situation? Thanks.

**Comment by FredrikOseberg** [comment]
> I want to know if unleash server is down. Would the sdk return error, or just return False.
> 
> e.g. if (unleash.isEnabled('proxy.demo')) { // do something }
> 
> Should I catch exception in my code specifically for this situation? Thanks.

It would simply return false. This would only apply however if the unleash server is down when you start your application, otherwise the SDK would continue to run on the last known state that it fetched from unleash and keeps in it's internal cache. 

In addition, we have recently improved the bootstrapping capabilities of our SDKs, which means that should the unleash server be unreachable for any reason on startup, the SDK can initialize with an alternative state. This work is ongoing, but you can see which SDKs support this functionality here: https://docs.getunleash.io/sdks

**Comment by ljcljc** [comment]
Thanks for the reply. For the cache you mentioned, is it in memory or disk? For example, my application is on server, and I reboot my application/server, would the cache remain old value? Thanks.

**Comment by sighphyre** [comment]
The caching is both disk and memory - a snapshot is held in memory, which is what's read from during runtime for toggle resolution. But it's also written to disk and should be checked on load. So yes, the cache should retain the old value. The notable exception here is the Rust SDK, which doesn't have disk caching.

**Comment by sighphyre** [comment]
This seems to be answered and there's no more activity, going to close this for now
