### ISSUE TITLE
Documentaion on offline working?

### ISSUE THREAD

**Issue by broomfn** [Unleash/unleash#1405]
Hi,

We have a mobile app project where users are often offline for days on end and the mobile application has to work offline and then sync when they are back online, I'm just wondering how this might (or if it's even currently possible) work if we tried to integrate unleash feature flags, presumably unleash need to talk to a server every time the code is run/loaded up?

Thanks

Neil

**Comment by thomasheartman** [comment]
Hi, @broomfn! 🙋🏼 

That's a great question! And indeed something we should document better. The mobile SDKs (Android, iOS, React (Native)) aren't perfectly aligned here, so I'll try and outline the differences below, but I'll start with the bits that are shared. Out of curiosity, what language/SDK would you be using for writing your apps?

> presumably unleash need to talk to a server every time the code is run/loaded up?

All Unleash clients cache and evaluate their feature toggle states locally. That means that they don't talk to a server at all when they check toggle statuses. Instead, they try to sync with Unleash (or in the case of mobile apps: the Unleash Proxy) at predetermined intervals. Unleash / the proxy provides the client with the currently enabled feature toggles for each particular user.

Because all evaluation is done locally, Unleash will continue to work just fine without network connectivity. The only time you might need an internet connection (this varies by SDK, more on that below) is at startup for the initial sync. All feature toggles will evaluate to `false` until Unleash can get an initial payload from somewhere.

Now, on to the individual SDKs: 

The Android SDK supports loading toggle states from a file, and also for polling from a file. You can also store a proxy response locally and use that stored response to bootstrap the SDK without network connectivity. In other words, the Android SDK can function just fine without ever connecting to the network, but you will obviously still need to either fetch or bundle the toggles at some point for them to activate.

The React SDK is just a wrapper around the JS proxy client, and [as specified in the readme, it supports bootstrapping on startup](https://github.com/Unleash/unleash-proxy-client-js#bootstrap). So while it doesn't necessarily support polling from a file, it's otherwise on par with the Android SDK in terms of offline capabilities.

The iOS SDK is not as fully-fledged as the Android SDK, so it does not support bootstrapping from a file (although you may be able to work around this somehow).

------

Does that answer your question? Let me know if you've got any followups ☺️

**Comment by broomfn** [comment]
HI @thomasheartman,

Many thanks for the very detailed explanation, I think that answers my question and alleviates my concerns :-)

> Out of curiosity, what language/SDK would you be using for writing your apps?

It would be Ionic so I'm guessing that would fall under the JavaScript client?

**Comment by thomasheartman** [comment]
That's great! I'm adding this to the list of things that we should document better, so thanks for the question too!

> It would be Ionic so I'm guessing that would fall under the JavaScript client?

I don't have much experience with Ionic, but if it's the JS client, then it should work just fine! Same goes for that as for the React client as specified above.

**Comment by dbowling** [comment]
@thomasheartman I just found Unleash and had similar questions, so I'll tack on one more thing that I hadn't been able to figure out until I read your reply above. What client behavior happens if there is an Unleash server outage?

If I understand your answer, clients who have already synced will continue functioning as-is, while any new clients that aren't established would fall back on the default variant, which appears to be a disabled/falsey flag.

Using the example in the React Client readme, that would mean that if the API couldn't be reached for an initial value, your example would render `<AnotherComponent/>` regardless of any configuration done for `travel.landing`. Almost like a circuit breaker.

```ts
import { useFlag } from '@unleash/proxy-client-react';

const TestComponent = () => {
  const enabled = useFlag('travel.landing');

  if (enabled) {
    return <SomeComponent />
  }
  return <AnotherComponent />
};

export default TestComponent;
``` 

Does this seem right?

**Comment by thomasheartman** [comment]
@dbowling Thanks for asking! This too should be clarified in the documentaion - I'll try and add a note about it today.

In short, though, you're perfectly right. If the server goes down, already activated clients will just keep working. New clients will fall back to the defaults. In the case of front-end clients, that'll be false, while on server-side clients, you can provide a default value in the case of a missing toggle 😄
