### ISSUE TITLE
Should the variants returned ro clients be sorted by names?

### ISSUE THREAD

**Issue by nhathongly** [Unleash/unleash#1412]
The list of variants in each feature returned to clients are not sorted. It makes the client's `GetVariant` sometimes returns different variants with the same `UnleashContext`. I think it should be sorted so that the `GetVariant` works more reliably

https://github.com/Unleash/unleash/blob/d264f30fa00469ee348b64761aa4a9166fe1646c/src/lib/db/feature-toggle-client-store.ts#L148

**Comment by sighphyre** [comment]
I think this might be by design, depending on your situation. If you don't have stickiness set up for variants then this is the correct behaviour, they're typically randomised on on the client SDK side if a toggle has no stickiness set or there's no user id and no session id. If you do have stickiness set up then this very well may be a bug though.

I can absolutely help either assist you get stickiness setup or get a bug report logged if you're up for giving us some more information on how your configuration is set up or if you have a minimal reproducible example?
