### ISSUE TITLE
default environment is disabled while creating API token

### ISSUE THREAD

**Issue by prabhutw** [Unleash/unleash#1562]
### Describe the bug

I am using opensource version of unleash 4.10.0. default environment is disabled and manually enabled it for the default project. Eventhough, while creating API token, "default" option is disabled in the dropdown "Which environment should the token have access to?" 

### Expected behavior
Able to select "default" environment while creating API token

_No response_

### Logs, error output, etc.

getting this error while creating via API call, 

```
{"isJoi":true,"name":"BadDataError","details":[{"message":"Client token cannot be scoped to disabled environments"}]}
```

### Screenshots

<img width="435" alt="Screenshot 2022-05-04 at 5 49 02 PM" src="https://user-images.githubusercontent.com/25531027/166680752-9dcb66e9-527d-4689-84d5-d5c9ac9b1bde.png">

### Unleash version

4.10.0

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by FredrikOseberg** [comment]
You're right. This is indeed a bug, as we have transitioned OSS away from the default environment you are not supposed to be able to turn this environment on at the project level. The rest of the system is acting normally, because this an action it does not expect. 

May I ask what your use case is for using the default environment instead of using the built in production/development environments?

**Comment by FredrikOseberg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project overview can turn on Default environment even when the default environment is turned off globally](https://trello.com/c/hpf5AUbe/1117-project-overview-can-turn-on-default-environment-even-when-the-default-environment-is-turned-off-globally)

**Comment by prabhutw** [comment]
Thanks for the response @FredrikOseberg 
We have deployed our application in 3 envs. So thought of using default, development and production.
