### ISSUE TITLE
eventHook 'feature-updated'

### ISSUE THREAD

**Issue by Pfuenzle** [Unleash/unleash#1605]
### Describe the feature request

I am currently trying to send a message to a webhook on certain events using the eventHook feature.
The events supported by this method are `'feature-created', 'feature-updated', 'feature-archived' and 'feature-revived'`, according to [https://docs.getunleash.io/deploy/configuring_unleash](url). However, when trying with unleash version v4.3 or newer, only `'feature-created', 'feature-archived' and 'feature-revived'` are triggering the event-hook. For versions lower than this, its working just fine. On the [Webhook addon page](https://docs.getunleash.io/addons/webhook) it says, that `feature-updated` has been deprecated because of the transition to environments.

I guess this is also the case for the eventHook then?
If so, is there a way to restore the event or achieve a similiar solution to be notified when a feature has been updated?

Thanks a lot,
Pfuenzle

### Solution suggestions

Add back `feature-updated` or a similiar event.

**Comment by thomasheartman** [comment]
Hey, @Pfuenzle! Thanks for the question 😄 You're right; the documentation definitely isn't good enough around this (and not up to date either). I don't actually know right away what the right way forward is here, but let me go and do some research and get back to you (probably some time tomorrow)? ☺️

**Comment by thomasheartman** [comment]
I'm back 🙋 And I got some more information for you! In short: 

When we released v4.3 we deprecated the `feature-updated` event in favor of more fine-grained events. At the same time, we also deprecated the `eventHook` feature because it saw so little use. However, it seems we forgot to update the docs 😳 Because it was deprecated, it never got the updates for the events.

As a replacement for the `eventHook`, we added the generic webhook events. The webhook addon should be a full replacement for the `eventHook` feature (let me know if it doesn't work somehow or doesn't cover some of your use cases).

Regarding the `feature-updated` events: As mentioned on the webhook addon page, you now get a whole lot more events. So instead of listening to one general giant event, you'll need to listen to a number of smaller, more targeted events. You should still be able to get all the same updates, however.

> If wanted, I could update the documentation when we found a solution (or at least add a deprecation notice)
Absolutely; we'd love that ❤ 

Let me know if this works for you or if you need any more information ☺

**Comment by Pfuenzle** [comment]
Hey,
thanks for the detailed answer.
Good to know its deprecated, so I have to use the addon anyways :D
The reason I used the eventHook instead of the webhook addon was that I need to use a proxy to connect to non-LAN services and I did not see a way to use a proxy with the addons, so it wasnt really viable for me. I then solved it by implementing an eventHook, which then uses a proxy to make a POST request using axios, which worked fine.

After reading your answer, I looked for alternatives and found the node module `node-global-proxy`, which allows me to set a global proxy, which also lets the requests of the webhook addon use it.
Using the module, the addon works fine and I can say goodbye to the eventHooks 😄 

Not sure if this is a common use-case to have to use a proxy, but I think using another module to achieve this is pretty reasonable. I will make a pull request for the updated docs later today.

Thanks for the quick and helpful answer and have a great day.

**Comment by thomasheartman** [comment]
> The reason I used the eventHook instead of the webhook addon was that I need to use a proxy to connect to non-LAN services and I did not see a way to use a proxy with the addons, so it wasnt really viable for me. 
> [...]
> [I] found the node module node-global-proxy, which allows me to set a global proxy, which also lets the requests of the webhook addon use it.

Oh, that's an interesting use case, and I'm not sure we've come across that very often. I know that _I_ haven't heard about it, at least 💁🏼 But very happy to hear that you found a solution to it 🥳 

> I will make a pull request for the updated docs later today.

Fantastic! Feel free to go ahead and tag me (or request a review) and I'll look at it as soon as I find the time for it 🙋🏼 

And thank you too for reporting this and finding a solution (and doubly so for agreeing to write it up! 🙌🏼 ) 😄
