### ISSUE TITLE
Toggle "Created Invalid Date"

### ISSUE THREAD

**Issue by theneva** [Unleash/unleash#205]
![image](https://cloud.githubusercontent.com/assets/1404650/22385196/ffb505a6-e4d1-11e6-8704-b99d469d9798.png)

Wat

**Comment by ivarconr** [comment]
the root cause seems to be that we use timestamp without time zone as column type. We should probably use with timestamp with time zone 
https://www.postgresql.org/docs/9.5/static/datatype-datetime.html. 

I believe it would be possible to just write a few alter-table migrations for timestamp columns. Will have a go at this later.
