### ISSUE TITLE
Should not be possible to delete or change built-in strategies.

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#209]
The API should reject changes on strategies marked as built-in.

**Comment by aes** [comment]
*Why?*

If you don't quite trust the users, making a system for different access levels is just asking for trouble. 

If you're worried that someone will delete "default", then how about having that be the behavior when the list of predicates is empty? (would also solve #204)

**Comment by vsandvold** [comment]
@aes good point about default strategy, ref #204. It could work as an empty state, contrary to what I said earlier.

**Comment by ivarconr** [comment]
I like your suggestion on how to handle the `default strategy` being the strategy used when no other strategies are defined. This needs to be intuitive in the UI though!

You are probaly correct; it might be OK to let users to delete [built-in strategies](https://github.com/Unleash/unleash/blob/master/docs/activation-strategies.md); It might just be that we need to mark them better in the UI, so that the user understands that these are expected to be implemented by client implementations. What do you think?

**Comment by aes** [comment]
From an engineering perspective, it's usually a good principle to keep code and data as separate as possible. Requiring some kind of fixtures may be useful to maintain orthogonality, but avoiding it is even better.

From a product utility perspective, I don't see any reason to remove possibilities. To the contrary, I can easily imagine a scenario where devs choose the strategies and tell users to only use the ones available, e.g so userWithId isn't available, because it's not relevant. In this situation the absence of this built-in provides clarity to the user.

That said, I think there should be a checklist of features to implement before calling it a feature-complete client. (yes, I have / am working on a Python client, I might do more, it's a fun toy problem)

**Comment by ivarconr** [comment]
> From a product utility perspective, I don't see any reason to remove possibilities.
agreed. I still think it would be valuable to highlight whether it is a "standardized" strategy or not. 

> That said, I think there should be a checklist of features to implement before calling it a feature-complete client. (yes, I have / am working on a Python client, I might do more, it's a fun toy problem)

Awesome, will be nice to see some code at some point.
