### ISSUE TITLE
bug: Variants "Fix Setting" has Incorrect Behavior

### ISSUE THREAD

**Issue by sebastian-bury** [Unleash/unleash#2222]
### Describe the bug

Using the "fix" percentage on variants causes issues. Setting to 33.33% can cause an error (event logs show the weight being set as 333.29999999999995 while the other (variable set) percentage is set to 667.
This can also be seen by using any more than 1 decimal point. Using two or more causes the weights to add up over 1000. This causes the UI to show a percentage, but the actual weight is different. Ex. setting a variant to 55.555% causes one weight to be 505.55 and the other to be 495. This means the total is 1000.55, meaning 495/1000.55 is actually 49.47%. Not a huge issue but it is incorrect. 
![Screenshot 2022-10-20 at 15 29 41](https://user-images.githubusercontent.com/101799760/197137368-1dcd8b4c-f4fc-499d-b780-3e9a8aa22647.png)
![Screenshot 2022-10-20 at 15 26 22](https://user-images.githubusercontent.com/101799760/197137372-a889623e-7151-4697-a0fc-fa2c7676e124.png)

### Steps to reproduce the bug

1. Create a feature toggle
2. add at least two variants
3. set one variant percentage manually with more than 1 decimal point
4. check event logs for actual weights set in the system 

### Expected behavior

I would expect weights to accurately add up to 1000 and to be accurate in the UI so users can correctly set up experiments. 

### Screenshots

![Screenshot 2022-10-20 at 15 29 41](https://user-images.githubusercontent.com/101799760/197137733-bc36a683-6349-4835-b099-4db9727340aa.png)
![Screenshot 2022-10-20 at 15 26 22](https://user-images.githubusercontent.com/101799760/197137739-4310e414-a51f-43f0-b87b-7dc2d6e419bc.png)

### Unleash version

4.16.1

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

**Comment by gastonfournier** [comment]
I've opened a PR to fix this, but since I'm not a Javascript expert, I'd love to have input from more seasoned engineers (because the solution looks ugly, but I didn't find a suitable alternative)

**Comment by gastonfournier** [comment]
Hi @sebastian-bury according to [our docs](https://docs.getunleash.io/reference/feature-toggle-variants#variant-weight), we only support 1 decimal point for decimals. The fact we're allowing customers to enter more than 1 decimal point could be considered a bug. The question would be: do they really need more than 1 decimal? Maintaining more than 1 decimal doesn't look like a complicated task (it may have some rough edges though), but limiting the input to 1 decimal is a much simpler solution, but we'd be limiting their flexibility.

Consider that for a customer with 10M users, 0.01% represents 1000 users. First, I don't think we have many customers with 10M users, and second, 1000 out of 10M is probably not meaningful (statistically speaking). So I'm not sure how useful would be to support more than 1 decimal point.

**Comment by sebastian-bury** [comment]
@gastonfournier that is true. I have had several customers ask for the ability to have multiple decimals there as part of trainings. For example, when A/B testing they would like to do 1/3 of users in a category (33.33%) or 2/3, or things like that where having at least 2 decimal places would be very useful. I understand it is not a large amount of their populations, but for their experimentation they would really appreciate multiple decimal places.

**Comment by gastonfournier** [comment]
@sebastian-bury 33.3% is also 1/3, so I'm not really sure if we need that. I agree, that it's more natural to think of 2 decimals (or even leave it up to the user), but right now it'd require some changes in our systems which might not be trivial. Starting with understanding why the use of integers:
1. If we want to keep using integers, we need to make a migration on the database to support more digits
2. If we get rid of integers and switch to floats, we need to be more careful and probably remove the additional complexity of using integers (i.e. all the multiplications and divisions to transform from integers to floats).
In both cases, our documentation has to be updated.

My advice would be to open that up as a new feature request so we can assess if it's worth the effort. For the moment, the easiest thing to do is to [enforce the 1-digit limitation](https://github.com/Unleash/unleash/pull/2749) because as you mention in this issue, anything with more than 1 decimal digit will cause this misbehaviour. If someone asks about this, we can always redirect them to [our docs](https://docs.getunleash.io/reference/feature-toggle-variants#variant-weight) and tell them that we're considering it.

Would that be a reasonable resolution?

**Comment by sebastian-bury** [comment]
@gastonfournier makes sense to me, not worth it for that much effort :) 
I will open this as a feature request!

**Comment by gastonfournier** [comment]
Thanks! It seems like a reasonable feature, interesting but with a low ROI. Anyway, it's good to discuss this with a wider audience to validate my assumptions
