### ISSUE TITLE
Server logs to detect, if client asks for unspecified feature?

### ISSUE THREAD

**Issue by 1developer1** [Unleash/unleash#248]
Hi there, 

is there already a possibility to get unleash server logs to the console to detect, if clients are asking for unspecified features?

Maybe I am blind.
Sorry for that. 

Greetings

**Comment by ivarconr** [comment]
Hi, thanks for showing an interest! 

The server cannot do this because of the design decision where all the logic is implemented in the clients and not in the server to make to make it super fast, read more about [how it works in this blog](http://bytes.schibsted.com/unleash-features-gradually/)

Because the clients are sending metrics back to the server we can however detect if the clients use toggles the server does not know about. This is presented in the unleash ui under the application details section. 

![shot](https://user-images.githubusercontent.com/158948/28032597-5d76b52c-65ab-11e7-8a7f-60701bf0eca7.png)

**Comment by 1developer1** [comment]
Thank you for your feedback!
