### ISSUE TITLE
Querying/Filtering

### ISSUE THREAD

**Issue by tfheen** [Unleash/unleash#251]
In some cases, I'm only interested in certain features, such as those matching a regex or those that are enabled.  It would be useful if one could query for just those.

**Comment by ivarconr** [comment]
Agreed, this sounds like a great enhancement of the client API.

**Comment by ivarconr** [comment]
We don't see the real usecase for this and could also have negative effects on metrics integration in clients.

We can reopen if someone can provide more concrete examples on why unleash needs to provde query/filtering.

**Comment by tfheen** [comment]
The concrete use case is how we shift traffic between legacy and new infrastructure where there is a component that looks at all enabled toggles matching a pattern and then changes weights in haproxy accordingly.  The alternative is to load all toggles and do the filtering on the client side, but it feels wasteful, especially when you have lots of toggles.  In this setup, unleash is the source of truth for what amount of traffic should go where, and this will obviously vary on a per-application basis.

**Comment by ivarconr** [comment]
Not exposing the disabled toggles might lead to clients to not report metrics on disabled toggles, because they might belive they don't exist. This is not how metrics should work. 

We can provide filtering per name, but I after discussing a bit with @sveisvei I don't thing this can be a raw regex, as this can have big security and performance concerns if we get this wrong. We can hovever provide defined filters, such as "startsWith" etc. 

How would such a query filter typically look like? 

1. `http://unleash.svc.prod.finn.no/api/client/features?name^=<prefix>`
2. `http://unleash.svc.prod.finn.no/api/client/features?name-starts-with=<prefix>`
3. `http://unleash.herokuapp.com/api/client/features?filter=startsWith(name, prefix)`

**Comment by ivarconr** [comment]
or just:
1. `http://unleash.svc.prod.finn.no/api/client/features?name=<prefix>*`

**Comment by tfheen** [comment]
Your last suggestion would work fine for us, or maybe `/features?prefix=$prefix`? I don't really mind exactly what the name is.
