### ISSUE TITLE
"Flag Groups" and Browser clients 

### ISSUE THREAD

**Issue by mrsufgi** [Unleash/unleash#255]
As I understand, today, a client registered by using the API or be some kind of a service using the client implementations.
A response would be an image of the settings in the dashboard and the client should use the response JSON and return values from the flags object (implementing the 'strategies' on the SDKs).

I actually really like the software design here but I was wondering, how can I use Unleashed for client-side browser applications with millions of anonymous clients? As I've seen in the roadmap for v3 A/B and experiments system is planned, but as I understand, clients will still receive the entire flag settings and strategies and assign flags with the client implemented logic. Do you consider some kind of mechanism for assigning clients to buckets on the Unleashed server and return only a subset of flags with a flag groupId (hashed ofc) back to clients, omitting the need for client to do the logic locally, and fallback to a set of defaults if he fails to fetch flags from the server?  

Maybe creating a proxy server to Unleashed would be the best approach?  
As for Unleashed-server being a single source of truth, the proxy would be updated as flag settings changes (push or pull) and clients would interact with the proxy for flags and metrics.

As those are only blurred lines and mere suggestions I would really like to contribute to this project.

**Comment by ivarconr** [comment]
> As I understand, today, a client registered by using the API or be some kind of a service using the client implementations.

Yes this is correct :)

The whole design idea for Unleash is that the client should be the smart part, making Unleash scalable and easier to adopt by anyone. We do not plan on changing this in the near future.

That said, as you point out, this dose make it a bit more complex to use in client side apps. We kyst Aldo remember that the toggle configuration might contain somewhat sensitive data (userids, emails, etc). In FINN we have chosen the proxy approach for our native applications, when the apps queries all the toggles their are interested in together with context details. The app will store these locally (on web one can use local storage for this). This allow us to still have custom strategies and keep the implementation server side. We also have support for A/B testing via custom strategies and the app gets instructed on tracking details it should add. It does however not solve the unleash usage metrics, as the native apps only queries the proxy once in a while. I don't feel that these metrics are critical, but we might need to extend the clints so that the user can supply these numbers.
