### ISSUE TITLE
Unleash Client Api not returning strategies when used with an admin api key

### ISSUE THREAD

**Issue by marinarierav** [Unleash/unleash#2702]
## Describe the bug
Requests to this endpoint `/api/client/features` are not returning feature strategies, but the docs state it should: https://docs.getunleash.io/reference/api/legacy/unleash/client/features

I also discovered the strategies are missing when using an admin api key, but they are retrieved successfully when using a client api key.

## Steps to reproduce the bug
In Node.js:
```
  const config = {
    method: "get",
    url: `https://app.unleash-hosted.com/purple/api/client/features`,
    headers: {
      Accept: "application/json",
      "Accept-Encoding": "application/json",
      Authorization: apiKey, // using an admin api key
    },
  };
  const response = await axios(config);
  let { features } = response.data;

  console.log(features[0]); // All features are missing strategies
```

## Expected behavior
I was expecting the behavior to be the same, regardless of which key type I use. That is, i was expecting the strategies to be returned when using an admin api key.

### Logs, error output, etc.
No response

### Screenshots
The first command is run with an admin key. The second is run with a client key.
The output is the strategies of the same flag:
- Admin key -> no strategies collected
- Client key -> strategies collected ok
<img width="922" alt="Captura de pantalla 2022-12-15 a las 11 11 01" src="https://user-images.githubusercontent.com/47626039/207833853-6d8bde8d-4ade-4a4c-96af-64e976fa8b8d.png">

### Additional context
I am making requests to unleash server-side, that's why I was using an admin api key. I expected it to work the same way.

### Unleash version
4.18.4

### Subscription type
Enterprise

### Hosting type
Hosted by Unleash

### SDK information (language and version)
No SDK, Node.js directly making requests to Client Api

# Huge thanks in advance !

**Comment by thomasheartman** [comment]
Hey, @marinarierav 👋🏼 

I think what you are seeing is the expected behavior. I'm going to go out on a limb and guess that the strategies you are looking for **are not in the default environment** (that is, the environment called "default"), and that that's why you're not seeing them. I'll explain this in more detail below, but the tl;dr: is **don't use admin tokens with client endpoints**. Instead **use client tokens configured for that specific environment**.

There is a longer explanation about the background of tokens and environments following this, but I'm curious about your use case: why are you using an admin token and not a client token if you're working on a client? Does the admin token offer you something you need?

And now for the wall of text 🤓 📚 

## Admin tokens, client tokens, and environments

Unleash has a few different kinds of API tokens, each with different purposes and privileges. For the purposes of this, we'll look only at admin and client tokens. Refer to the [API tokens reference doc](https://docs.getunleash.io/reference/api-tokens-and-client-keys#admin-tokens) for more info.

**Admin tokens** are designed to be used with the admin API and to create, update, and delete features, projects, etc. Because of this, they are always encoded for all environments (as described in the ["format" section of the API keys doc](https://docs.getunleash.io/reference/api-tokens-and-client-keys#format)). They have access to all projects and all environments. This makes them well suited for managing your entire Unleash instance.

**Client tokens** are designed to be used by clients that only read feature configuration (either SDKs or homegrown clients). They are read-only for feature configuration and can only be given access to **a single environment**. This environment is encoded into the key to make it easier to see at a glance.

### The "default" environment

When you get features with the client API (`api/client/features`), Unleash will return the feature configuration for the environment encoded into your API token. 

For client tokens, this is easy, because they only have access to a single environment. 

But what about admin tokens? Because they have access to all environments, you might think that they'd get the configuration for all environments, but that's not how it works. Instead, we need to look at how Unleash has evolved:

Unleash's [environments feature](https://docs.getunleash.io/reference/environments) was introduced in Unleash 4.3. Up until then, Unleash didn't have a notion of environments, and the way to use environments was to encode it into the Unleash context. (Side note: this is also why all SDKs have `environment` listed as a configuration variable even if it doesn't affect the Unleash environment. But that's a story for another day.)

But when Unleash introduced environments, it was important for us that we didn't break anything for existing customers and that existing API keys kept working. So we introduced the "default" environment. This special environment is only available to users who upgrade from a version of Unleash that doesn't have environments to a version that **does** have environments. Any toggle configuration you had in your Unleash system before the data migration would be moved to the default environment and any API keys you created before the migration would still work for that environment.

This is also when the new API token format appeared. Old client tokens would continue to work with the default environment, and admin tokens were also assigned to the default environment when using the client API. And I suspect this is why, when you try and use the client API with an admin key, you're getting all the features, but you're not getting any strategies. Presumably, you're trying to fetch strategies for a specific environment (that isn't the "default" environment), but because there's no strategies defined for the default environment, the list is empty.

## Suggested solution

Based on what I've said above, I really recommend that you use client tokens if you're writing a client yourself. If you're writing an Unleash client like the Node client, then that is going to be the right thing in the vast majority of use cases.

In addition to being able to narrow the token permissions down to a single environment and a pre-defined list of projects, using a client token would also prevent a malicious actor from wreaking havoc on your Unleash instance if it got lost.

### Potential workaround

However, if you're writing a client that can also manage Unleash (like a full or partial replacement for the Admin UI), then you'll need an admin token. In that case, though, I'm curious as to why you would need to fetch client feature configurations? Maybe the system is also acting as a proxy?

In the case that you _need_ an admin token for the system and you can't use client tokens for these requests, you should still be able to target a specific environment. When you're making the request to the endpoint, I think you should be able to add an `environment` query parameter (e.g. `/api/client/features?environment=development`). However, this is not an intended use case, and we may remove that ability in the future, so I wouldn't rely on that if you can avoid it.

**Comment by marinarierav** [comment]
Hi @thomasheartman 
Thank you soooo much!!!!!! I more than appreciate your detailed explanation. That totally makes sense now. I'll use a client api key for now and we can close the issue 👍

**Comment by thomasheartman** [comment]
Great! Glad you found it helpful 😄 Let me know if you have any other questions ☺️
