### ISSUE TITLE
Ability to restrict/enable action by user

### ISSUE THREAD

**Issue by panel** [Unleash/unleash#289]
My organization wants to use Unleash in order to separate the shipping of code to production (technical concern) from releasing features to our customers (business concern). To that end, I'd like to restrict certain action by group. For example:

- Create feature -> Developer
- Edit feature/set strategy -> Product
- Toggle feature -> Product
- View Feature -> All
- Archive Feature -> Product
- Delete Feature -> Developer

There are different ways of implementing (ACL, RBAC, etc), but my main ask is to be able to leverage information stored in an external IdP (eg. AD, OneLogin, etc.) to populate privs/groups/whichever schema authorization is handled with.

**Comment by ivarconr** [comment]
You would theoretically be able to achieve this with a custom middleware, registered via the [preHook](https://github.com/Unleash/unleash/blob/master/docs/getting-started.md#2-or-programmatically) option. But you would then need to restrict all relevant paths yourself, which might be cumbersome to maintain. 

;;
My initial thought is that one could add "groups" to the user when they authenticate, which can be fetched from any external system. I need to think about this. 

I would appreciate a concrete suggestion on how Unleash could provide support for assigning groups to users, and what each group is allowed to do in the system.

**Comment by panel** [comment]
A concrete way forward would be for Unleash to have individual privileges for different admin actions (eg. view all features, toggle feature) and make that privilege registry available in a postAuth hook where I can house some business logic that can map information from my IdP to privileges available in Unleash and attach the appropriate privileges to the User object. From there I can register a `preRouterHook` that allows me to validate that the user has the proper privs to take the action they are attempting.

I'm proposing this _a_ possible solution. I'm certainly open to others. Some of the key features I see with this solution are:

- Consumers are free to create their own roles based on their business needs without adding additional strain on Unleash
- Unleash is only responsible for communicating its own capabilities rather than taking on new responsibilities.

I'm extremely new to this project, but very excited about its potential. After collaborating and deciding if this is a valuable addition, I'm more than willing to attempt to create a working implementation to start iterating on.

**Comment by ivarconr** [comment]
I think you solution could work and are in line with what I have been thinking about. 

I wounder though if it would make sense to also have the use privileges available in the UI, so that the UI could disable actions the user is not allowed to do. It's kind of stupid if the user is allowed to open the "create feature form" but disallowed to submit it. 

My concrete thought was that Unleash could have a set of defined actions as you describe, some of these could be (:
- toggle.view _(I'm not totally sure if we actually need disable view rights, then you probably should not be allowed to use Unleash at all)_
- admin.all
- toggle.create
- toggle.enable
- toggle.edit
- toggle.delete
- strategy.create
- strategy.edit
- strategy.delete
- application.edit
- ...

Unleash could also have a concept of roles, which are defined by the users of Unleash. When the user creates a new role he can select which of the above actions that is enabled within each role. 

When a user signs in, the authentication hook should also assign appropriate roles to the user object. A user can have one or more roles. Each role has defined rights associated with them. The roles and associated actions for them and the user and his roles is available for frontend logic also, allowing the frontend to leverage that information to disable actions not applicable to the current user. 

On the backend all admin routes needs to verify that the current users has the required action rights to perform the desired action. 

Because not all users of Unleash would require roles one could implemented so that the user will get the admin role by default if no other roles are defined.

**Comment by panel** [comment]
If you think roles and privileges make sense to include as first class citizens within Unleash, I think that could make the implementation a bit more straightforward. I do think it makes sense to make the unauthenticated and/or the superuser case "just work." I found the extremely low barrier to getting the app up and running and my application connected quickly a very compelling feature.

I could see a first version where the `postAuth` hook is responsible for assigning permissions (defined actions) to a user. This could be carried to the UI via the UserProvider which would allow us to conditionally disable controls.

A follow up change could allow in app management of roles along with a default "superuser" role that gets applied to all authenticated users by default.

**Comment by panel** [comment]
I think this sounds great, and I'm excited to help out!

1. This definitely sounds like the most complex piece, and the part I feel like I'm least equipped to help out on. I'd be happy to be wrong here, though.
1. I don't think this necessarily needs to be implemented _after_ 1. The change seems relatively straightforward and consistent regardless of different architectures around privilege structure. I could probably take this on.
1. This probably needs to wait on 1 and 2 since it's for unions of those two sets.
1. If there doesn't already exist a generic `403` handler, we could implement one similar to the `401` handler where the producer could provide custom messaging. This seems like it could get started write away as well.

**Comment by ivarconr** [comment]
I can have a look at 1),  but it will take me some time, probably a week or so, as I'm currently home full time taking care of my son. It might be relevant to see these action in conjunction with [event-types](https://github.com/Unleash/unleash/blob/master/lib/event-type.js) used in the event history.

**Comment by panel** [comment]
If I can operate under the assumption that the only actions worth requiring authorization for are those where we're generating an audit log, I can work extending the User type and creating a middleware. Then it could be incremental expansion of actions that can be protected via auth and audited.

**Comment by ivarconr** [comment]
I would be awesome if you are able to do an example implementation. I was thinking that `ResourceAction` should at least have two properties:
- `resource`: identifying the resource granting access to. Could be `feature`, `strategy`, `application`, `event`. 
- `actions`: Should be a list of actions granted on the given resource. Could be `view`, `edit`, `delete`. We should also consider if it makes sense to have an wildcard type, `*`. Wildcards could be supported by the constructor, but always be expanded to mean all actions. 

The only thing I'm a bit unsure about is how specific actions should be. From your example I believe `create`, `view`, `edit` and `delete` should be sufficient to support all cases for feature toggles. (And you never actually deletes toggles in unleash, they are archived. This is to prevent from accidental reuse of a toggle in a new application.).

**Comment by ivarconr** [comment]
@panel Did you manage to look more in to this? I will be more than happy to review any suggestions you might have.

**Comment by ivarconr** [comment]
solved via #373
