### ISSUE TITLE
Make it possible to disable a strategy

### ISSUE THREAD

**Issue by tlevesque-ueat** [Unleash/unleash#3255]
### Describe the feature request

Currently there's no way to disable a strategy, you can only delete it, which also loses the associated constraints.
When multiple strategies are defined for a feature toggle, it would be useful to be able to disable them individually.

**Comment by thomasheartman** [comment]
Thanks, @tlevesque-ueat! Like with the [other issue you opened](https://github.com/Unleash/unleash/issues/3254), I think you have a very good point. Losing associated constraints and strategy configuration is especially pertinent. I'll bring it up internally and get back to you ☺️

**Comment by thomasheartman** [comment]
Hi! So we've talked about this a bit internally and there's some concerns that we'd need to think carefully about. This is especially regarding user-friendliness and how easy it is to understand the UI.

- If you have many strategies, how do we visualize it so that it's easy to see whether one is disabled or not? 

- Can you disable all strategies or is there a limit? As of today, you can't enable a feature without at least one strategy. Do we require you to always have **at least one enabled** strategy?

But for more information here, could you elaborate a bit more on your use case? 

And here's a workaround suggestion: if you always use gradual rollout strategies, then "disabling" the strategy would be equivalent to setting the rollout percentage to 0.  You'd still retain the constraints etc. Sure, you'd need to record the rollout % if it should be reset to the same level, but at least you're keeping everything else. 

Would that work for you?

**Comment by tlevesque-ueat** [comment]
Hi @thomasheartman,

Thanks for your reply.

> * If you have many strategies, how do we visualize it so that it's easy to see whether one is disabled or not?

Well, I'm not a UX designer, but I guess a visual clue like "gray out" the strategy could work. Just an idea.

> * Can you disable all strategies or is there a limit? As of today, you can't enable a feature without at least one strategy. Do we require you to always have **at least one enabled** strategy?

I guess it would make sense to always have at least one strategy enabled. Or, if you disable the only enabled strategy, disable the feature toggle as well.

> But for more information here, could you elaborate a bit more on your use case?

We have a new feature that we initially want to rollout selectively for certain users, based on a certain criteria (for the sake of this discussion, let's say it is "which payment method they use"). The user's payment method is not directly accessible to the app that will use the feature toggle, so instead, we'll specify user ids manually, based on their payment method.

So my plan was to add a strategy for each payment method, each with a constraint on the user ids. If we could disable a strategy, it would make it easy to enable/disable the feature for a given payment method (e.g. if we realize the new feature causes issues with Paypal users, we can disable it quickly), without having to check the payment method for each user to edit the constraint.
(it's the same scenario that also prompted my "named strategy" proposal)

This scenario might seem a little contrived, but I suspect being able to disable a strategy would also be useful in other situations.

> And here's a workaround suggestion: if you always use gradual rollout strategies, then "disabling" the strategy would be equivalent to setting the rollout percentage to 0. You'd still retain the constraints etc. Sure, you'd need to record the rollout % if it should be reset to the same level, but at least you're keeping everything else.

Thanks for the suggest, I didn't think of that! I only used standard strategies so far. In my scenario the rollout percentage would be either 0% or 100%. But yeah, I guess that could work.

The workaround I had in mind was less elegant (add a constraint that I know will always be false to disable the strategy)

**Comment by thomasheartman** [comment]
> Well, I'm not a UX designer, but I guess a visual clue like "gray out" the strategy could work. Just an idea.

Yeah, for sure. And to clarify, I wasn't really asking you to solve these issues. I was mostly just presenting the challenges to solve. That said, I **do** appreciate your input on them ☺️ 

> So my plan was to add a strategy for each payment method, each with a constraint on the user ids. If we could disable a strategy, it would make it easy to enable/disable the feature for a given payment method (e.g. if we realize the new feature causes issues with Paypal users, we can disable it quickly), without having to check the payment method for each user to edit the constraint.

Thanks for the extra context! That's certainly illuminating, both for this feature request and for the named strategies.

That said - and this is only tangentially related to issue itself - it sounds like you'll quickly end up with a lot of user IDs specified directly in Unleash in this case. We generally recommend that you don't use constraints/userID strategies in that way because it increases the amount of data Unleash has to transmit as explained in the [strategy constraint reference documentation](https://docs.getunleash.io/reference/strategy-constraints#limitations).  We're working on improving the docs around this at the moment, but our primary suggestions is to store the user IDs somewhere outside of Unleash and use something like Redis to populate a custom context field. In your case, I suppose the custom context field would be `paymentMethod` and you'd use Redis to map user ID to payment method. You can check out this repository for an example of [how to do the same thing with segments](https://github.com/sighphyre/UnleashAndRedis). 

> Thanks for the suggest, I didn't think of that! I only used standard strategies so far. In my scenario the rollout percentage would be either 0% or 100%. But yeah, I guess that could work.

Great! Yeah, that should effective let you disable the strategies you need. And if you only do 0 or 100 percent, then it sounds like it might cover that use case fairly well?

Thanks again 😄

**Comment by tlevesque-ueat** [comment]
> it sounds like you'll quickly end up with a lot of user IDs specified directly in Unleash in this case. We generally recommend that you don't use constraints/userID strategies in that way because it increases the amount of data Unleash has to transmit

Yes, but we don't intend to enable it for many users during the rollout phase. (and anyway the user id/payment method example is just to illustrate, it's not what we're actually doing)

> And if you only do 0 or 100 percent, then it sounds like it might cover that use case fairly well?

Yes, it does. Thanks!
