### ISSUE TITLE
Add the authoring hook earlier and without rendering the UI?

### ISSUE THREAD

**Issue by leftieFriele** [Unleash/unleash#346]
I think that the authentication hook is not working optimally right now as it renders the site for anyone (I know it doesn’t show content, but it still leaks the fact that you run unleash to everyone).
Would it make sense to have the sign in dialogue appear without displaying anything of the site itself?

**Comment by ivarconr** [comment]
It would be possible, but it will require separate page for login, otherwise the SPA-js bundle would still reveal that this is in fact `Unleash`. 

Actually with the current model, there is nothing stopping you to add a separate login-page, as part of the custom authentication hook. The way you would implement this would simply be to redirect on the "root resource" (`/`) to a custom login-page, then the current user is not authenticated, and handle login process in your own custom way. 

Side note: I think #342 is kind of related to this, and I need to think a bit on what's the "frontend" and "backend" responsibilities in the authentication process.
