### ISSUE TITLE
Can built Unleash API Controller in spring project code base ??

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash#384]
Can be built Unleash API in spring project code base to avoid if Unleash server is down and somehow local cache is not available

**Comment by ivarconr** [comment]
Can you please elaborate? I don't understand the question.

**Comment by vkatoch2000** [comment]
I mean to say API server reside with in unleash server.

If we can pull only unlease API in our code base and still using client to access our server to avoid any downtime in future

**Comment by ivarconr** [comment]
The client is designed with resilience in mind. It will keep all toggles in memory and poll the server regularly. It will even store copy of latest toggle state to disk so that your app will get correct state across restarts. 

You are also encouraged to use sane fallback when you ask for a toggle state from the client (in case unleash does not know about your toggle).

**Comment by vkatoch2000** [comment]
storing cache file in EC2 instance is fragile, it will be removed when deployed to new instance , i am thinking about the case when we don't have cache file and Unleash server is down...
How this will work ?
