### ISSUE TITLE
Question - How we can use Unleash for a frontend client ( react )

### ISSUE THREAD

**Issue by ROUDALI** [Unleash/unleash#414]

**Comment by ivarconr** [comment]
Hi,

Unleash does not ship browser client unfortunately. There are good reason not to do that:

1. The poll mechanism will drain the battery of mobile clients
2. You end up exposing all toggles and variants to everyone
3. It could be security flaw

What we do at FINN.no is a small small proxy between Unleash and our browser and native clients which returns feature toggles in the context of a specific user. I hope to open source such a proxy at some point. 

![image](https://user-images.githubusercontent.com/158948/55379992-19666980-551f-11e9-9731-1e8068876921.png)


The proxy could do push based updates. We currently do not do that, but have plans for experimenting with this. Currently we do pull based (but with much lower frequency than a server side SDK.

**Comment by ivarconr** [comment]
We have a few client's using next.js and thus I have been looking in to how to ease the integration and make sure that SSR works and propagates toggles to the view. I really want to avoid that intial-render flicker.  

I made a small PoC library for this: 
https://github.com/Unleash/next-unleash

Feedback welcomed! 
(Keep in mind that I have been using next.js for a week)

/cc @ROUDALI, @brianatrium, @ROUDALI, @pPanda-beta, @sveisvei, @SimenB, @elhoyos

**Comment by andreas1327250** [comment]
I still don't get it how it makes a difference for security or battery-performance if I query unleash or an unleash-proxy from a client (e.g. app or browser) device - can someone explain this to me?

What is your unleash-proxy (only an internal thing?) doing that makes its API better suited for client devices than the unleash-api?

**Comment by ivarconr** [comment]
As part of the SaaS offering we are now providing a [proxy](https://www.unleash-hosted.com/articles/the-unleash-proxy) and a thin [js client](https://github.com/unleash-hosted/unleash-proxy-client-js) for consuming the proxy-api.

It's better for **security** because it will only expose toggles enabled for that specific user. It will not show all toggles with all configuration (which may include specific userIds, emails etc).

The current js-client will not be better for **battery-performance** in itself as it still does background polling. We are however defaulting to a much lower poll-frequency, which reduces the chattiness. (we are considering SSE, but I'm not totally convinced the battery-benefits are that great, it must somehow keep the radio open to maintain the SSE connection, while in a polling scenario it can shut it down between the polls).

It is however much better in terms of **bandwidth usage**, as pre-evalueted and only active toggles is sent to the client.

**Comment by ivarconr** [comment]
https://docs.getunleash.io/sdks/unleash-proxy
