### ISSUE TITLE
Can not Deploy Unleash

### ISSUE THREAD

**Issue by lonpalmer** [Unleash/unleash#420]
When trying to deploy unleash I get the following error:

[2019-04-10T19:20:14.884] [ERROR] server-impl.js - Failed to migrate db { Error: No such driver found, please try to install it via npm install db-migrate-sqlite3 or npm install -g db-migrate-sqlite3

Steps:
npm install unleash-server
npm install
npm start

DATABASE_URL is set in the system env vars.

**Comment by lonpalmer** [comment]
More Info:  When I run the application it creates a file in the run directory which is named my db connection string!  So if my db connection string is 'xyz' it creates a file named 'xyz'.  It looks like an SQL Lite DB when it's opened because it starts SQLite format 3....

**Comment by ivarconr** [comment]
This happens because you are providing a database-url which is starting with `sqlite3`. Unleash only supports postgres today and the database url has to start with `postgres` because the prefix is used by [node-parse-database-url](https://github.com/pwnall/node-parse-database-url) which is used by Unleash. 

This is a valid db-url:
`postgres://user:password@localhost:5432/unleash`

This is **NOT** a valid db-url:
`sqlite3://user:password@localhost:5432/unleash`

**Comment by ivarconr** [comment]
Closed due to inactivity.

**Comment by lonpalmer** [comment]
> This happens because you are providing a database-url which is starting with `sqlite3`. Unleash only supports postgres today and the database url has to start with `postgres` because the prefix is used by [node-parse-database-url](https://github.com/pwnall/node-parse-database-url) which is used by Unleash.
> 
> This is a valid db-url:
> `postgres://user:password@localhost:5432/unleash`
> 
> This is **NOT** a valid db-url:
> `sqlite3://user:password@localhost:5432/unleash`

Nope, I'm not.  My database url doesn't have the word "sqlite3" anywhere in it.

**Comment by ivarconr** [comment]
I find this super weird. 

1. Can you verify the output of `> echo $DATABASE_URL`
2. What happens if you specify DATABASE_URL as part of npm start: `DATABASE_URL=postgres://unleash_user:passord@localhost:5432/unleash npm start`
