### ISSUE TITLE
Non boolean toggles

### ISSUE THREAD

**Issue by johnryan** [Unleash/unleash#471]
Hi! I've been investigating Unleash and it looks really great.

I was wondering if there was a recommended approach for non boolean toggles. This seems similar to the variants feature but it doesn't seem to have all the knobs to control who sees what. I read the docs here: https://unleash.github.io/docs/beta_features

And was wondering how I might be able to set a "default" with overrides based on various criteria.

For instance, if I wanted the default to be "orange", but to manually add an override to "blue" for a UserID: 123 is this possible?

Thanks!

**Comment by ivarconr** [comment]
Hi, thanks for showing interest in this project! 

> For instance, if I wanted the default to be "orange", but to manually add an override to "blue" for a UserID: 123 is this possible?

Yes, this is exactly what variants do for you. In order to achieve this behaviour you would define a toggle with 3 variants: `default`, `orange` and `blue`. For the `blue` variant you would add userId override for "123" to make sure this user will always get the "blue" variant. 

Please note that variant support is currently only implemented in the Java, Node.js and Ruby client.

**Comment by johnryan** [comment]
Got it, thanks for the insight.

Today, in the case where I added two variance, "orange" and "blue" the user override would supersede the 50/50 weight correct?

**Comment by ivarconr** [comment]
yes of course.

**Comment by johnryan** [comment]
Got it, thanks!
