### ISSUE TITLE
Feature Request: Allowing application level mapping to feature toggles and customized evaluation of strategies

### ISSUE THREAD

**Issue by thisisronak** [Unleash/unleash#540]
Hey Ivar, 

Request the implementation of the following features. Let me know if they are already available or on your roadmap.

1) Application level mapping/authorization to access its feature toggles: Looking at the database schema it is evident that there is no relationship between registered applications on the server and the features created. Is it possible to introduce this constraint (can be optional) where features created programmatically belong to the respective applications only.  

2) Customized evaluation of strategies and greater control over taking a union or intersection of the participating strategies. I stumbled upon [#442](https://github.com/Unleash/unleash/issues/442) which seems like a valid solution but would it be available for the open source version as well.

As a sidenote, if the above isn't in your immediate priority list would you be open to Merge requests?

Edit: + 3) Additionally, any plans to introduce paginated apis to fetch all features and if there is a max limit to the number of toggles which can be created?

**Comment by ivarconr** [comment]
1) This on our roadmap. We have not decided yet whether this will be an enterprise feature or also available as part of open-source. 
2) We have decided to keep this as an enterprise feature for now. 
3) Not really. I have never seen any real need for this as most companies (I have seen) usually never have more than a few hundred active feature toggles. That said as part of our plans for 1) we also think it makes sense to limit toggles expose to applications where they only will get relevant toggles based on the project they belongs to.

**Comment by zivyatziv** [comment]
A few questions came up to mind regarding this:
1. How can you identify an application? If application A created a feature and application B wants to use it, would it be sufficient that it simply changes it's `appName` in the `config` to `A` ?
1.1. Yes? --> Are we okay with this behaviour? Do we consider it safe?
1.2. No? --> Then maybe clients should have a "secret" which they share when they want to be marked as a certain application, more like a "username" and "password", in which the `appName = username` and `secret = password`
2. What about inserting TLS layer to Unleash?
3. I agree with the whole pagination thing. Right now Unleash uses an eager load to load all the features, if you have more than 100 features it'll load ALL of them, rather than just a portion. I suggest creating some sort of dictionary that will be updated by on-going-requests, we could leverage the search in the frontend to create a sort of a query to narrow the amount of features.
4. Adding a pagination to the UI with the ability to define how many items per page the user wants to see, this could be applied by providing a `token` and a `nextToken` like many service providers out there.
