### ISSUE TITLE
feat:  Survive DB Outages

### ISSUE THREAD

**Issue by mmcfarland-novetta** [Unleash/unleash#550]
If access to the Postgres DB is lost, Unleash currently crashes.

It would be beneficial if it Unleash could stay alive through DB outages, and provide the last known flag states until the it successfully reconnects to the database.

**Comment by ivarconr** [comment]
I think this can be solved pretty easily by introducing a small flag and memorization of the last known feature toggles. Also we need to configure the metrics to cache locally, without storing to db during the outage. If someone picks this up I will be more than happy to assist on the details.

**Comment by ZeeFiix** [comment]
a stupid question: why does it have to be that the unleash remains functional when the database is not accessible?

I know this is a heretical question, but the client sdk's implement a client-side cache to survive that ....

Personally, it bothers me more that when the client is started, the client cannot "warm up" the cache with standard values which should be used instead of viewing all toggles as "false".

It is not just the problems of losing the database connection that are exceptional cases. It can also be a network problem. Then the clients cannot reach the server at all. In this case it doesn't matter that the server process continues to run with its own cache.

**Comment by ivarconr** [comment]
A valid point @ZeeFiix and I think this issue raises the question for two different features that probably should be solved independently: 

1. Unleash should not crash when a database connection fail/times-out/crashes
  Network is unreliable and connections are closed. Unleash should retry, and at least not crash even if a single db-query fails.  
2. Unleash should be able to server client SDKs, event if database is unavailable
  I think this is a more questionable feature given the comment from @ZeeFiix.  It could make sense for some scenarios, but would also make sure we keep control of only returning the toggles matching the API query. E.g. We are allowing SDKs now to only request feature toggles for a specific project, or containing specific tags. This is currently handled on the DB layer as part of the query. Should Unleash support these queries as well during the db-outage?

**Comment by ZeeFiix** [comment]
Thought more unconventionally:

There is an Unleash Client SDK that implements a client-side cache. I think you know that ;-)

Why don't you take your own client SDK and ask your own server process about the feature toggle states?

Why is this client not also offered as an http endpoint, which then queries the direct endpoint in the background and which persists in the "client" cache on the server side?

If the "real" server endpoint does not work in the background due to communication problems, the toggle information feature is still available and you use your own fail-safe feature

... You can continue to think about code reuse, code hygiene ... and and and.

just thought so absolutely freely.

Sounds like a dirty hack. 
But if i think it through carefully and, of course, illuminate the necessary adjustments to the design from the front and back, then I find it charming (... with the knowledge that I currently have about unleash (which is not really deep yet))

**Comment by ivarconr** [comment]
https://github.com/Unleash/unleash/issues/550

**Comment by ivarconr** [comment]
Unleash does no longer crash when Postgres crashes. 

Your points are still valid @ZeeFiix, but they would better be handled in a separate issue.

**Comment by diegoNutmeg** [comment]
> Unleash does no longer crash when Postgres crashes.
> 
> Your points are still valid @ZeeFiix, but they would better be handled in a separate issue.

After which version Unleash not longer crashes? 
I have been testing it with version `3.10.1` and crash for me.


```
web_1  | [2022-01-17T14:39:39.497] [INFO] server-impl.js - Unleash has started. { address: '::', family: 'IPv6', port: 4242 }
web_1  | (Unleash) started on 4242
web_1  | [2022-01-17T14:40:25.557] [WARN] db-pool.js - Connection Error: Connection ended unexpectedly
web_1  | [2022-01-17T14:40:25.560] [WARN] db-pool.js - Connection Error: Connection ended unexpectedly
web_1  | [ERROR] Error: getaddrinfo ENOTFOUND db
web_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
nm-unleash-service_1 exited with code 1
Aborting on container exit...
```

I am testing a DB maintenance window
