### ISSUE TITLE
Hidden breaking changes

### ISSUE THREAD

**Issue by qwelias** [Unleash/unleash#625]
Points from the changelog that should have bumped major version number:
- `feat: require node >= 12` this is breaking
- `fix: add settings column to postgres` this one also was breaking for us as the application would crash without the table

**Comment by ivarconr** [comment]
Hi, thanks for reaching out!

> feat: require node >= 12 this is breaking

In hindsight i totally agree with you that this change should have been a major release. The reasoning for changing it was just because anything below node 12 is not active LTS anymore.

> fix: add settings column to postgres this one also was breaking for us as the application would crash without the table

This one is more a surprise to me, and Unleash should work without this column being present. I guess this becomes a problem because you are not allowing Unleash to migrate your database? 

I am not sure if it makes sense to always issue a new major release every time we change the database definition, as a lot of features requires changes to the database (new field, column, etc). but they should probably always be a feature release. What do you think?

I am sorry for your bad experience. I will learn from this and make sure to improve how we deal with changes.

**Comment by qwelias** [comment]
My bad on reporting the settings table as a breaking change -- we had an issue with configuration which affected migrations from running properly. So the only problem is the major node requirements bump. Thanks for feedback!

So I guess I could close the issue since there's probably no point in addressing the node requirements bump after the fact.
