### ISSUE TITLE
tech: Migrate to typescript

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#676]
To make it easier to maintain the project, and onboard new contributors we plan to migrate to TypeScript

**Comment by checketts** [comment]
@ivarconr I've been looking into this migration. It appears that it could be done in 3 stages:

1. Add Typescript compiler config and move all JS files into `src/` directory. Don't change change any file content/extensions yet
2. Begin converting JS file extensions to TS, allowing loosest conversion and only fixing minimal compilation issues. (Allow `any` for most calls, for example)
3. Enable strict Typescript and clean up issues as they are found.

I've tried steps 1 and 2 a few times, but since it will touch most files in the repository, I don't want to kick off a merge-conflict that will stall the project.

Do you have any recommendations? Or would you just prefer I send a PR (of step 1) and deal with the fallout?

**Comment by ivarconr** [comment]
Your suggested steps seems logical @checketts. 

I think this is a change the core team needs to collaborate on, but I feel comfortable on allowing your to take the first step (1.) on a separate branch. We have no large features planned for the unleash-server repo for the coming week (expect minor bug-fixes), so the timing is quite good actually.
