### ISSUE TITLE
unleash server sometimes returns http 502

### ISSUE THREAD

**Issue by LiranBinshtok** [Unleash/unleash#708]
hello we installed the unleash server on aws fargate behind ALB 
and once in a few hours we get an error Unleash Repository error: Response was not statusCode 2XX, but was 502.
how can we fix this?

**Comment by ivarconr** [comment]
Hi @LiranBinshtok, 

Which client SDK (type and version) are you using?

**Comment by LiranBinshtok** [comment]
nodejs, java,

**Comment by ivarconr** [comment]
502 is not a response that Unleash will typically return, so either there is a error between ALB and the Unleash instance, or the Unleash instance has crashed and is currently not available. [See the AWS docs for more details](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-502-issues).

Are you able to get the Unleash server logs?

**Comment by LiranBinshtok** [comment]
here are the logs but i do not see something useful there.

[log-events-viewer-result.txt](https://github.com/Unleash/unleash/files/5938960/log-events-viewer-result.txt)

**Comment by ivarconr** [comment]
Have you configured any health checks between your ALB and Unleash? Also you should enable ALB logs and see why it is unable to send the request to Unleash. I suspect there might be some errors in the configuration between ALB and Unleash.

60s should be fine, because the keepAlive timeout is configured to 61s in Unleash, but you could try to lower it to 30s

**Comment by LiranBinshtok** [comment]
i been playing with the idle timeout of the ALB for the past few weeks and it seems that once i set it to 4 seconds the error does not happen any more.
