### ISSUE TITLE
feat: Make js-proxy-sdk support React-Native Unleash

### ISSUE THREAD

**Issue by vedyed** [Unleash/unleash#785]
Hello,

Can anyone please tell me what library I can use to integrate Unleash into my react-native mobile application?

Does this package or https://github.com/unleash-hosted/unleash-proxy-client-js work?

**Comment by ivarconr** [comment]
Hi there @vedyed 

Currently it will not work fully out of the box as we need to adapt local storage and the fetching a bit. But the plan is it make it work with react native also. 

Would you be interested in collaborating on this?

**Comment by vedyed** [comment]
So, does that mean just replacing the `window.localStorage` with equivalent in react-native?
I think AsyncStorage can be an option. Please let me know if this is what you had in mind by storage. 

![image](https://user-images.githubusercontent.com/81049702/114937788-1fbc9b00-9df3-11eb-996f-90b224e90887.png)

**Comment by ivarconr** [comment]
Yes, this is exactly what I am talking about. 

Would it be possible to use `fetch` in ract-native, or is there some other kind of http abstraction that would work?

I think we should open an issue in the proxy-client repo and follow up there!

**Comment by vedyed** [comment]
`fetch` would also work. We generally use `axios` for react-native but fetch would do the job too.

**Comment by vedyed** [comment]
I agree, we should try updating https://github.com/unleash-hosted/unleash-proxy-client-js/blob/master/src/storage-provider-local.ts which means adding new package(s). I tried this but had issue where the `node_modules` for unleash-proxy-client were not getting populated after `npm install` in the project. 

I'll work on this soon and test my changes thoroughly. If all good, will post the changes

![image](https://user-images.githubusercontent.com/81049702/115070491-db400680-9ea9-11eb-8955-729baa642e01.png)

**Comment by amrdraz** [comment]
@vedyed any update on this, I'm interesting in picking this up

**Comment by amrdraz** [comment]
> I agree, we should try updating https://github.com/unleash-hosted/unleash-proxy-client-js/blob/master/src/storage-provider-local.ts which means adding new package(s). I tried this but had issue where the `node_modules` for unleash-proxy-client were not getting populated after `npm install` in the project.
> 
> I'll work on this soon and test my changes thoroughly. If all good, will post the changes
> 
> ![image](https://user-images.githubusercontent.com/81049702/115070491-db400680-9ea9-11eb-8955-729baa642e01.png)

Looking at the code I can already see we can pass a storageProvider  when creating an unleash client

in react native the window object exists so if we just don't use the LocalStorageProvider and instead pass one using it's interface we should be fine.

the only real change that needs to happen is to have the get function signature be async and have the constructor behave accordingly [at this line](
https://github.com/unleash-hosted/unleash-proxy-client-js/blob/b8ad1a31f7768bdbc308a01218153efdcbfe0a7f/src/index.ts#L94)

        this.toggles = this.storage.get(storeKey) || [];

which is also not really required since it doesn't block the initialisation, we can just add some extra check that we did load storage, but other than all toggles being false (on start) until we load storage or network (which is a different issue), storage isn't blocking for react native

**Comment by amrdraz** [comment]
@ivarconr 
Regarding fetch it  also looks like it should work fine (will try later) , but in general we may want to consider implementing an httpProvider, similar to the storageProvider pattern used, in order to accommodate other more advanced configurations for example in react native people setup certificate-pinning using a different library. (we could overriding the global fetch object but that's messy) so our http provider needs to just be aware of our header and url configurations as well as return the data object.

on a performance note, we may consider especially on android, not using setInterval and using requestAnimation frame instead.

if we will support other means of fetching server data in realtime using sockets for example we could consider an adapter for them as well, but that's irrelevant.

**Comment by ivarconr** [comment]
thanks. We plan to open-source the proxy soon. Would you @amrdraz  be able to contribute on making a react-native support work with the proxy? I am happy to add you to the private proxy repository to ease you testing.

**Comment by ivarconr** [comment]
> on a performance note, we may consider especially on android, not using setInterval and using requestAnimation frame instead.

Indeed. This makes sense in the browser as well.

**Comment by amrdraz** [comment]
> thanks. We plan to open-source the proxy soon. Would you @amrdraz be able to contribute on making a react-native support work with the proxy? I am happy to add you to the private proxy repository to ease you testing.

Sure I’d like that, I’m very excited about this project a feature flag service is essential for modern development

**Comment by adeyahya** [comment]
I think it already works with react-native by providing `IStorageProvider` to `UnleashClient`. for example using shared-preferences

```tsx
import SharedPreferences from 'react-native-shared-preferences';
import { UnleashClient } from 'unleash-proxy-client';

const unleash = new UnleashClient({
    url: 'https://eu.unleash-hosted.com/hosted/proxy',
    clientKey: 'your-proxy-key',
    appName: 'my-webapp',
	storage: {
		save: (name: string, data: any) => SharedPreferences.setItem(name, data),
		get: (name: string) => SharedPreferences.getItem(name, (val) => val)
	},
});
```

I think we just need update the docs for this, wdyt @vedyed

**Comment by ivarconr** [comment]
[unleash-proxy-client-js](https://github.com/unleash-hosted/unleash-proxy-client-js)1.2.0 should be compatible with react-native 👍🏼

**Comment by amrdraz** [comment]
I’ll try this Thursday and if not no later then this Saturday

**Comment by amrdraz** [comment]
I confirm that it work and created an example repo https://github.com/amrdraz/example-unleash-react-native

**Comment by amrdraz** [comment]
in the repo I created a [react package hook implementation ](https://github.com/amrdraz/example-unleash-react-native/blob/main/app/react-unleash.tsx)in case you were looking for a. possible implementation  

see using the provider [App](https://github.com/amrdraz/example-unleash-react-native/blob/main/app/App.tsx) and [one of the consumers  ](https://github.com/amrdraz/example-unleash-react-native/blob/main/app/Features.tsx)

**Comment by amrdraz** [comment]
I can transfer ownership  if it's useful

**Comment by ivarconr** [comment]
> I can transfer ownership if it's useful

This would be very helpful. I will make sure you keep full access to the repo

**Comment by ivarconr** [comment]
Let me know if I can assist in any way @amrdraz

**Comment by amrdraz** [comment]
Sorry I got started on my work week, I thought about it and figured a react
native example just belongs in the react proxy  sdk

I will be submitting a PR Wednesday latest to that repo with a starting
proposal for the react sdk with the examples in it

Was writing tests on Saturday and ran out of time.

**Comment by ericledonge** [comment]
Hello, I've just used the Proxy Client React for a React Native App. I've made a pull request to enhance the documentation: https://github.com/Unleash/proxy-client-react/pull/20

Is it enough for you or do you need me to make a project sample or is it enough with it. With the Proxy Client React and this PR, it is very easy to understand how to use unleash with React Native.
